<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="59618" started-at="2018-08-07T06:40:35Z" finished-at="2018-08-07T06:41:35Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="59618" started-at="2018-08-07T06:40:35Z" finished-at="2018-08-07T06:41:35Z">
      <class name="testcase.android.bodyMatches">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcase.android.bodyMatches@204f30ec]" name="setUp" is-config="true" duration-ms="18899" started-at="2018-08-07T13:40:35Z" finished-at="2018-08-07T13:40:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testtestFollow()[pri:0, instance:testcase.android.bodyMatches@204f30ec]" name="testtestFollow" duration-ms="39740" started-at="2018-08-07T13:40:54Z" finished-at="2018-08-07T13:41:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [White Impress Body Serum] but found [Baby Bath]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [White Impress Body Serum] but found [Baby Bath]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at testcase.android.bodyMatches.testtestFollow(bodyMatches.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testtestFollow -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcase.android.bodyMatches@204f30ec]" name="tearDown" is-config="true" duration-ms="938" started-at="2018-08-07T13:41:34Z" finished-at="2018-08-07T13:41:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcase.android.bodyMatches -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
